# Generated by Django 3.2.2 on 2021-05-06 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.TextField(null=True)),
                ('desciption', models.CharField(max_length=150)),
                ('price', models.IntegerField(null=True)),
                ('user_type', models.TextField(null=True)),
                ('name_auther', models.TextField(null=True)),
                ('release_date', models.TextField(null=True)),
                ('rate', models.TextField(null=True)),
                ('comments', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_me', models.TextField(null=True)),
                ('birth_date', models.DateField(null=True)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
